### ISSUE TITLE
Still not workin in 1.6.5

### ISSUE THREAD

**Issue by Ic3x** [MCMainiac/GameModeControl#14]
I was trying to use the plugin on my paper Server. Still getting the message that it cant load :(
would be nice to be able to use it.

`
[13:18:12 INFO]: [GMC] Enabling GMC v1.6
[13:18:12 ERROR]: Error occurred while enabling GMC v1.6 (Is it up to date?)
java.lang.NoSuchMethodError: 'void org.bstats.bukkit.Metrics.<init>(org.bukkit.plugin.Plugin, int)'
        at de.ricardoboss.gmc.Main.onEnable(Main.java:119) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-597]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-597]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-597]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-597]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-597]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:591) ~[patched_1.16.5.jar:git-Paper-597]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-597]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-597]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-597]
        at java.lang.Thread.run(Thread.java:834) [?:?]

[13:18:12 INFO]: [GMC] Disabling GMC v1.6
`

**Comment by ricardoboss** [comment]
Looking into it

**Comment by AguZz** [comment]
Hi, any updates on the issue? I'm trying to use the plugin on a modded 1.16.5 server, but as soon as the server starts, it disables it with this "warning":

[Server thread/INFO] [de.ricardoboss.gmc.Main/]: [GMC] Enabling GMC v1.6[21:08:43] [Server thread/INFO] [de.ricardoboss.gmc.Main/]: [GMC] Enabling GMC v1.6[21:08:43] [Server thread/INFO] [/]: [GMC] Forcing gamemode SURVIVAL on player join[21:08:43] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling GMC v1.6 (Is it up to date?)java.lang.NoSuchMethodError: 'void org.bstats.bukkit.Metrics.<init>(org.bukkit.plugin.Plugin, int)' at de.ricardoboss.gmc.Main.onEnable(Main.java:119) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[forge:7e29f765-296df566-9fb885e8] at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413) ~[forge:7e29f765-296df566-9fb885e8] at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:429) ~[?:?] at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349) ~[?:?] at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221) ~[?:?] at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?] at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?] at java.lang.Thread.run(Thread.java:829) ~[?:?][21:08:43] [Server thread/INFO] [de.ricardoboss.gmc.Main/]: [GMC] Disabling GMC v1.6

**Comment by ricardoboss** [comment]
@AguZz Sorry, I'm not actively supporting this plugin anymore. Maybe I will again in the future, but not for now. You'll have to look for alternatives.
