### ISSUE TITLE
java.lang.NullPointerException with craftbukkit-1.8.8

### ISSUE THREAD

**Issue by kevinmoilar** [MCMainiac/GameModeControl#6]
Hi. I get an error after installing GMC vBeta 1.3.8 starting craftbukkit-1.8.8 (using openjdk-8-jdk):

[11:21:42 INFO]: [GMC] Enabling GMC vBeta 1.3.8
[11:21:44 ERROR]: Error occurred while enabling GMC vBeta 1.3.8 (Is it up to date?)
java.lang.NullPointerException
        at com.mcmainiac.gmc.Main.log(Main.java:173) ~[?:?]
        at com.mcmainiac.gmc.Main.log(Main.java:157) ~[?:?]
        at com.mcmainiac.gmc.Main.checkForUpdates(Main.java:132) ~[?:?]
        at com.mcmainiac.gmc.Main.onEnable(Main.java:54) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:404) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:342) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:314) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:406) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:370) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:325) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:235) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:504) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by ricardoboss** [comment]
I'll have a look at this later.

**Comment by ricardoboss** [comment]
@kevinmoilar I would recommend that you wait until 1.3.9 is out. It seems that I am unable to find the bug in 1.3.8. 1.3.9 will be released either later this day or tomorrow. Anyway, thanks for your report!
