### ISSUE TITLE
Unhandled exception executing command 'gm0' in plugin GMC vBeta 1.3.9

### ISSUE THREAD

**Issue by kevinmoilar** [MCMainiac/GameModeControl#7]
Hi,
The new release is still not working for us on craftbukkit-1.8.8 with openjdk on a debian (8) server.

openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2~bpo8+1-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)

It would be great if you could have a look, let me know if you need more info,
Thanks and best regards, k

=======================================================

[08:54:22 INFO]: belfastchild issued server command: /gm0
[08:54:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'gm0' in plugin GMC vBeta 1.3.9
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:140) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:620) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1106) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:966) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:37) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(SourceFile:9) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:673) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:629) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:537) [craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
Caused by: java.lang.NullPointerException
        at de.mcmainiac.gmc.Main.log(Main.java:136) ~[?:?]
        at de.mcmainiac.gmc.utils.CGM.set(CGM.java:29) ~[?:?]
        at de.mcmainiac.gmc.helpers.Commands.Gamemode(Commands.java:120) ~[?:?]
        at de.mcmainiac.gmc.Main.onCommand(Main.java:85) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[craftbukkit-1.8.8.jar:git-Bukkit-e1ebe52]
        ... 15 more

**Comment by ricardoboss** [comment]
I need the while Log. Please put the 'latest.log' on pastebin or something similar.

**Comment by kevinmoilar** [comment]
here: https://paste.debian.net/901691/

**Comment by ricardoboss** [comment]
Okay, so I tried redirecting the console output, which seems to be the problem here. Have a look at this f38b95a. To test this, I would like you to try the `GMC-1.3.10-debug.jar` file: [MCMainiac/GameModeControl/debug/versions/GMC%201.3.10-debug.jar](https://github.com/MCMainiac/GameModeControl/blob/debug/versions/GMC%201.3.10-debug.jar).

Please tell me if this fixes the issue, otherwise we have to try something else :)

**Comment by kevinmoilar** [comment]
Thanks man! This fixes the problem, issue resolved! :bowing_man:

**Comment by ricardoboss** [comment]
Okay, fix will be included in the next update.
